spring:
  application:
    name: eureka
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/



---
spring:
  profiles: 7001
server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001

---
spring:
  profiles: 7002
server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002

---
spring:
  profiles: 7003
server:
  port: 7003
eureka:
  instance:
    hostname: eureka7003